version: '3'
services:
    redis:
        image: redis:3.2-alpine
    postgres:
        image: mdillon/postgis:9.6-alpine
        environment:
            POSTGRES_PASSWORD: "password"
            POSTGRES_DB: "wocky"
    wocky:
        depends_on:
            - redis
            - postgres
        image: 773488857071.dkr.ecr.us-west-2.amazonaws.com/hippware/wocky:latest
        ports:
            - "5222:5222"
            - "8080:8080"
        environment:
            WOCKY_DB_NAME: "wocky"
            WOCKY_DB_HOST: "postgres"
            WOCKY_DB_USER: "postgres"
            WOCKY_DB_PASSWORD: "password"
            REDIS_HOST: "redis"
            REDIS_PORT: "6379"
            MANDRILL_API_KEY: ""
            HONEYBADGER_API_KEY: ""
            WOCKY_DB_WATCHER_BACKEND: "WockyDBWatcher.Backend.Direct"
            DAWDLE_BACKEND: "Dawdle.Backend.Local"
            KUBE_POD_NS: "local-dev"
        command: ["dev_startup"]
        hostname: "wocky-private"
        domainname: "local-dev.svc.cluster.local"
