---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wocky-config
  namespace: wocky-testing
  labels:
    app: wocky
    env: testing
data:
  WOCKY_ENV: prod
  WOCKY_INST: testing
  WOCKY_HOST: testing.dev.tinyrobot.com
  WOCKY_IQ_CRASH_RESPONSE: error_with_dump
  WOCKY_TROS_S3_BUCKET: wocky-kube-tros-testing
  WOCKY_PUSH_ENABLED: "false"
  WOCKY_ENABLE_BYPASS: "true"
  WOCKY_ENABLE_FACTORY_INSERT: "true"
  WOCKY_CC_LOOKUP_METHOD: "hardwire"
  WOCKY_CC_HARDWIRE_VAL: "US"
  WOCKY_DB_HOST: db.dev.tinyrobot.com
  WOCKY_DB_NAME: wocky_testing
  WOCKY_DB_USER: wocky_testing
  DAWDLE_SQS_MESSAGE_QUEUE: wocky-db-watcher-testing.fifo
  DAWDLE_SQS_DELAY_QUEUE: wocky-dawdle-testing
  WOCKY_ENTER_DEBOUNCE_SECONDS: "0"
  WOCKY_EXIT_DEBOUNCE_SECONDS: "0"
  WOCKY_EXPIRE_TRANSIENT_USERS_AFTER_DAYS: "1"
  AWS_ACCESS_KEY_ID: AKIAISCBKX42EUVSVXAQ
  HONEYBADGER_ENV: testing
  REPLACE_OS_VARS: "true"
  REDIS_HOST: master.wocky-redis.byxmud.usw2.cache.amazonaws.com
  REDIS_DB: "3"
  REDIS_SSL: "true"
