apiVersion: v1
kind: ConfigMap
metadata:
  name: wocky-config
  namespace: wocky-testing
data:
  WOCKY_ENV: prod
  WOCKY_INST: testing
  WOCKY_HOST: testing.dev.tinyrobot.com
  WOCKY_IQ_CRASH_RESPONSE: error_with_dump
  WOCKY_TROS_S3_BUCKET: wocky-kube-tros-testing
  WOCKY_S3_REGION: us-west-2
  WOCKY_S3_ACCESS_KEY_ID: AKIAJOOG6KJT7K4EHNCA
  WOCKY_ENABLE_PUSH: "false"
  WOCKY_INDEXING_SYSTEM: test
  WOCKY_USER_INDEX_NAME: ""
  WOCKY_BOT_INDEX_NAME: ""
  WOCKY_ENABLE_BOT_REPORT: "false"
  WOCKY_ENABLE_BYPASS: "true"
  WOCKY_DB_HOST: wocky-testing.cx7fev3pluk8.us-west-2.rds.amazonaws.com
  WOCKY_DB_NAME: wocky_testing
  WOCKY_DB_USER: postgres
  AWS_ACCESS_KEY_ID: AKIAJF36QNVCKI2EWLLQ
  HONEYBADGER_ENV: testing
  CLOUDWATCH_KEY_ID: AKIAJUCGS5NJU6ALDHKA
  CLOUDWATCH_REGION: us-west-2
  CLOUDWATCH_INSTANCE: ""
  REPLACE_OS_VARS: "true"
