apiVersion: v1
kind: Service
metadata:
  name: wocky-private
  labels:
    app: wocky
spec:
  ports:
    - port: 8080
      name: http
    - port: 5222
      name: xmpp
    - port: 5269
      name: xmpp-s2s
    - port: 4369
      name: epmd
    - port: 9100
      name: distribution
  selector:
    app: wocky
  clusterIP: None
