apiVersion: v1
kind: Service
metadata:
  name: wocky-service
spec:
  ports:
    - port: 5222
      targetPort: 5222
      protocol: TCP
      name: http
  selector:
    app: wocky
  type: LoadBalancer
