apiVersion: v1
kind: Service
metadata:
  name: wocky-public
  labels:
    app: wocky
  annotations:
    # service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: 'true'
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: 'tcp'
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 5222
      targetPort: 5222
      protocol: TCP
      name: xmpp
    - port: 5280
      targetPort: 5280
      protocol: TCP
      name: xmpp-ws
  selector:
    app: wocky
  type: LoadBalancer
