apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wocky
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: wocky
    spec:
      containers:
        - name: wocky
          image: hippware/wocky:2017-08-24T073905Z
          ports:
            - containerPort: 5222
            - containerPort: 8080
            - containerPort: 5269
            - containerPort: 4369
            - containerPort: 9100
          args: ["foreground"]
          envFrom:
            - configMapRef:
                name: wocky-config
            - secretRef:
                name: wocky-secrets
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      imagePullSecrets:
        - name: dockerhub
