apiVersion: batch/v1
kind: Job
metadata:
  name: wocky-migration
spec:
  template:
    metadata:
      name: wocky-migration
    spec:
      containers:
        - name: wocky
          image: hippware/wocky:latest
          args: ["migrate"]
          envFrom:
            - configMapRef:
                name: wocky-config
            - secretRef:
                name: wocky-secrets
          env:
            - name: KUBE_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KUBE_POD_NS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      # Do not restart containers after they exit
      restartPolicy: Never
