apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: wocky-db-maintenance
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: wocky
              image: 773488857071.dkr.ecr.us-west-2.amazonaws.com/hippware/wocky:latest
              imagePullPolicy: Always
              args: ["db_maintenance"]
              envFrom:
                - configMapRef:
                    name: wocky-config
                - secretRef:
                    name: wocky-secrets
              env:
                - name: KUBE_POD_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.podIP
                - name: KUBE_POD_NS
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
          imagePullSecrets:
            - name: amazonecr
          # Do not restart containers after they exit
          restartPolicy: Never
