---
- name: Deploy Wocky
  hosts: app
  become: True
  become_user: wocky
  vars:
    erlang_deploy_name: wocky
    erlang_deploy_shared_folders:
      - { src: 'log', path: 'log' }
      - { src: 'mnesia', path: 'mnesia' }
  pre_tasks:
    - name: Capture the build version
      become: False
      local_action: shell ./version
      register: ver_result

    - name: Set release version
      set_fact:
        erlang_deploy_release_version: "{{ ver_result.stdout }}"

  roles:
    - erlang-deploy
