apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: wocky-loc-share-expire
  namespace: wocky-staging
  labels:
    app: wocky
    mod: loc_share_expire
    env: staging
spec:
  schedule: "0/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: wocky
            mod: loc_share_expire
            env: staging
        spec:
          restartPolicy: Never
          containers:
            - name: wocky
              image: 773488857071.dkr.ecr.us-west-2.amazonaws.com/hippware/wocky:<%= current_sha %>
              args: ["loc_share_expire"]
              envFrom:
                - configMapRef:
                    name: wocky-config
                - secretRef:
                    name: wocky-secrets
              env:
                - name: KUBE_POD_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.podIP
                - name: KUBE_POD_NS
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
