---
apiVersion: v1
kind: Service
metadata:
  name: wocky-private
  namespace: wocky-load
  labels:
    app: wocky
    env: load
spec:
  ports:
    - port: 8080
      name: http
    - port: 5222
      name: xmpp
    - port: 5269
      name: xmpp-s2s
    - port: 4369
      name: epmd
    - port: 9100
      name: distribution
  selector:
    app: wocky
    env: load
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: wocky-public
  namespace: wocky-load
  labels:
    app: wocky
    env: load
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: 'false'
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'false'
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '300'
    service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: 'false'
    service.beta.kubernetes.io/aws-load-balancer-access-log-emit-interval: '5'
    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-name: 'wocky-load-access-logs'
    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-prefix: ''
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: 'tcp'
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: 'arn:aws:acm:us-west-2:773488857071:certificate/f0b89f70-89db-400f-8431-2280fa518c2d'
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: '443,5223'
spec:
  externalTrafficPolicy: Local
  ports:
    - port: 443
      targetPort: 8080
      protocol: TCP
      name: https
    - port: 5223
      targetPort: 5222
      protocol: TCP
      name: xmpps
  selector:
    app: wocky
    env: load
  type: LoadBalancer
