---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wocky-config
  namespace: wocky-next
  labels:
    app: wocky
    env: next
data:
  WOCKY_ENV: prod
  WOCKY_INST: next
  WOCKY_HOST: next.dev.tinyrobot.com
  WOCKY_IQ_CRASH_RESPONSE: error
  WOCKY_TROS_S3_BUCKET: wocky-kube-tros-next
  WOCKY_PUSH_ENABLED: "true"
  WOCKY_ANDROID_PACKAGE_NAME: "com.hippware.android.tinyrobot.staging"
  WOCKY_APP_STORE_ID: "1198202376"
  WOCKY_IOS_BUNDLE_ID: "com.hippware.ios.ChatStaging"
  WOCKY_ENABLE_FACTORY_INSERT: "true"
  WOCKY_PUSH_APNS_TOPIC: "com.hippware.ios.ChatStaging"
  WOCKY_PUSH_FCM_PACKAGE: "com.hippware.android.tinyrobot.staging"
  WOCKY_PUSH_URI_PREFIX: "tinyrobotStaging"
  WOCKY_ENABLE_BYPASS: "true"
  WOCKY_DB_HOST: db.dev.tinyrobot.com
  WOCKY_DB_NAME: wocky_next
  WOCKY_DB_USER: wocky_next
  WOCKY_EXPIRE_TRANSIENT_USERS_AFTER_DAYS: "1"
  DAWDLE_SQS_MESSAGE_QUEUE: wocky-db-watcher-next.fifo
  DAWDLE_SQS_DELAY_QUEUE: wocky-dawdle-next
  WOCKY_SMS_BACKEND: Wocky.SMS.Twilio
  AWS_ACCESS_KEY_ID: AKIAJYPIJ4FONNTYC3RQ
  TWILIO_ACCOUNT_SID: ACbfbd3863ab87b6d00d37de65e99dacd1
  HONEYBADGER_ENV: next
  REPLACE_OS_VARS: "true"
  BAMBOO_ADAPTER: Bamboo.MandrillAdapter
  REDIS_HOST: wocky-cache.byxmud.ng.0001.usw2.cache.amazonaws.com
  REDIS_DB: "4"
