---
apiVersion: v1
kind: Service
metadata:
  name: wocky-private
  namespace: wocky-next
  labels:
    app: wocky
    env: next
spec:
  ports:
    - port: 8080
      name: http
    - port: 4369
      name: epmd
    - port: 9100
      name: distribution
  selector:
    app: wocky
    env: next
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: wocky-public
  namespace: wocky-next
  labels:
    app: wocky
    env: next
spec:
  externalTrafficPolicy: Local
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: wocky
    env: next
  type: NodePort
