---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wocky-config
  namespace: wocky-us1
  labels:
    app: wocky
    env: us1
data:
  WOCKY_ENV: prod
  WOCKY_INST: us1
  WOCKY_HOST: us1.prod.tinyrobot.com
  WOCKY_IQ_CRASH_RESPONSE: error
  WOCKY_TROS_S3_BUCKET: wocky-kube-tros-us1
  WOCKY_PUSH_ENABLED: "true"
  WOCKY_PUSH_APNS_TOPIC: "com.hippware.tinyrobot"
  WOCKY_PUSH_FCM_PACKAGE: "com.hippware.android.tinyrobot"
  WOCKY_PUSH_LOG_PAYLOAD: "false"
  WOCKY_GEOFENCE_SAVE_LOCATIONS: "false"
  WOCKY_ENABLE_BYPASS: "false"
  WOCKY_SMS_BACKEND: Wocky.SMS.Twilio
  WOCKY_DB_HOST: db.prod.tinyrobot.com
  WOCKY_DB_NAME: wocky_us1
  WOCKY_DB_USER: wocky_us1
  DAWDLE_SQS_MESSAGE_QUEUE: wocky-db-watcher-us1.fifo
  DAWDLE_SQS_DELAY_QUEUE: wocky-dawdle-us1
  WOCKY_LOG_TRAFFIC: "false"
  AWS_ACCESS_KEY_ID: AKIAJBP24HT7F7HCD7GQ
  TWILIO_ACCOUNT_SID: ACbfbd3863ab87b6d00d37de65e99dacd1
  HONEYBADGER_ENV: us1
  REPLACE_OS_VARS: "true"
  BAMBOO_ADAPTER: Bamboo.MandrillAdapter
  REDIS_HOST: wocky-cache.byxmud.ng.0001.usw2.cache.amazonaws.com
  REDIS_DB: "1"
